/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3KghP0ptw2G
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"


import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <script src="https://checkout.razorpay.com/v1/checkout.js" async></script>
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;


export function Component() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Razorpay Payment</CardTitle>
        <CardDescription>Complete your payment securely with Razorpay.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="card-number">Card Number</Label>
          <Input id="card-number" placeholder="4111 1111 1111 1111" />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="expiry">Expiry Date</Label>
            <Input id="expiry" placeholder="MM/YY" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="cvv">CVV</Label>
            <Input id="cvv" placeholder="123" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="amount">Amount</Label>
          <Input id="amount" type="number" placeholder="100.00" />
        </div>
      </CardContent>
      <CardFooter>
        <Button
          onClick={() => {
            const options = {
              key: "YOUR_RAZORPAY_KEY_ID",
              amount: "100",
              currency: "INR",
              name: "Acme Inc",
              description: "Test Transaction",
              image: "https://example.com/your_logo.png",
              order_id: "order_12345",
              handler: function (response) {
                alert("Payment successful!")
              },
              prefill: {
                name: "Gaurav Kumar",
                email: "gaurav.kumar@example.com",
                contact: "9999999999",
              },
              notes: {
                address: "Razorpay Corporate Office",
              },
              theme: {
                color: "#3399cc",
              },
            }
            const rzp1 = new window.Razorpay(options)
            rzp1.open()
          }}
          className="w-full"
        >
          Pay
        </Button>
      </CardFooter>
    </Card>
  )
}
